### ISSUE TITLE
Add assistant chip to experiment details page

### ISSUE THREAD

**Issue by snopoke** [dimagi/open-chat-studio-docs#13]

**Comment by snopoke** [comment]
Thanks, the changes are great but I actually mean the main experiment page (e.g. under channels). For both assistant and pipeline experiments we could link to the assistant / pipeline.

**Comment by SmittieC** [comment]
Oh I see. Good idea! I'll add it

**Comment by SmittieC** [comment]
FYI: https://github.com/dimagi/open-chat-studio/pull/1007
